<a href="https://colab.research.google.com/github/tharak-bairneni/tmdb-eda-assignment/blob/main/tmdb_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:

import requests
import pandas as pd
import sqlite3

In [3]:
#Step 1 — API Call (Get 20+ Movies)

url = "https://api.themoviedb.org/3/discover/movie"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzY2I3MDliYWZiZmE0NjEzYzIxNjZiZWQ5NDI3ODM1MyIsIm5iZiI6MTc3NDM1NDgyMC4yODQ5OTk4LCJzdWIiOiI2OWMyODE4NGMyOGEwNGJiNzZjNzVmYzYiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.EJlh3wximCF7YvXm0EObkv1oM7-ZyIwPe5PGQbey7i8"
}

response = requests.get(url, headers=headers)

data = response.json()

# Extract movie list
movies = data['results']

In [14]:
#Step 2 — Convert to DataFrame

df = pd.DataFrame(movies)

# Select useful columns
df = df[['id', 'title', 'release_date', 'popularity', 'vote_average', 'vote_count', 'genre_ids']]

# Fix SQLite issue (list → string)
df['genre_ids'] = df['genre_ids'].astype(str)

df.head()

,id,title,release_date,popularity,vote_average,vote_count,genre_ids
0,1523145,Your Heart Will Be Broken,2026-03-26,718.2018,6.000,10,"[10749, 18]"
1,875828,Peaky Blinders: The Immortal Man,2026-03-05,290.8743,7.363,476,"[80, 18]"
2,83533,Avatar: Fire and Ash,2025-12-17,304.5720,7.260,1946,"[878, 12, 14]"
3,687163,Project Hail Mary,2026-03-15,298.5383,8.183,587,"[878, 12]"
4,1290821,Shelter,2026-01-28,291.7651,6.733,410,"[28, 80, 53]"

In [15]:
df.shape

(20, 7)

In [16]:
# Step 3 — Save to SQLite

conn = sqlite3.connect("movies.db")

df.to_sql("movies", conn, if_exists="replace", index=False)

conn.close()

In [17]:
#Step 4 — Load Data Back

conn = sqlite3.connect("movies.db")

df = pd.read_sql("SELECT * FROM movies", conn)

df.head()

,id,title,release_date,popularity,vote_average,vote_count,genre_ids
0,1523145,Your Heart Will Be Broken,2026-03-26,718.2018,6.000,10,"[10749, 18]"
1,875828,Peaky Blinders: The Immortal Man,2026-03-05,290.8743,7.363,476,"[80, 18]"
2,83533,Avatar: Fire and Ash,2025-12-17,304.5720,7.260,1946,"[878, 12, 14]"
3,687163,Project Hail Mary,2026-03-15,298.5383,8.183,587,"[878, 12]"
4,1290821,Shelter,2026-01-28,291.7651,6.733,410,"[28, 80, 53]"

In [18]:
#Step 5 — First 5 Rows

df.head()

,id,title,release_date,popularity,vote_average,vote_count,genre_ids
0,1523145,Your Heart Will Be Broken,2026-03-26,718.2018,6.000,10,"[10749, 18]"
1,875828,Peaky Blinders: The Immortal Man,2026-03-05,290.8743,7.363,476,"[80, 18]"
2,83533,Avatar: Fire and Ash,2025-12-17,304.5720,7.260,1946,"[878, 12, 14]"
3,687163,Project Hail Mary,2026-03-15,298.5383,8.183,587,"[878, 12]"
4,1290821,Shelter,2026-01-28,291.7651,6.733,410,"[28, 80, 53]"

In [19]:
#Step 6 — Summary Statistics

df.describe()

                 id  popularity  vote_average   vote_count
count  2.000000e+01   20.000000     20.000000    20.000000
mean   1.135781e+06  227.072810      6.974200   564.450000
std    3.272576e+05  136.226495      0.676037   631.317626
min    8.353300e+04  105.917100      5.800000    10.000000
25%    1.084228e+06  125.465700      6.400000   151.750000
50%    1.196248e+06  222.777200      7.055000   443.000000
75%    1.302404e+06  282.942150      7.423750   634.500000
max    1.582770e+06  718.201800      8.183000  2362.000000

In [20]:
# Step 7 — Movies per Genre (Important Fix)

# Convert string back to list
df['genre_ids'] = df['genre_ids'].apply(eval)

# Explode genres
genre_df = df.explode('genre_ids')

# Count
genre_count = genre_df['genre_ids'].value_counts()

print(genre_count)

genre_ids
53       8
878      7
12       6
28       6
35       6
80       5
27       5
16       3
18       3
10751    3
9648     3
10749    2
14       1
Name: count, dtype: int64

In [21]:
# Step 8 — Missing Values

df.isnull().sum()

id              0
title           0
release_date    0
popularity      0
vote_average    0
vote_count      0
genre_ids       0
dtype: int64